[package]
name = "lolicon_api"
license = "MIT"
authors = ["poly000"]
description = "Lolicon API wrapper in Rust"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.4"
thiserror = "1.0.26"
serde = { version = "1.0", features = ["derive"] }